// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xaajbbgdzikvyuqinysi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhYWpiYmdkemlrdnl1cWlueXNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MTk0MTQsImV4cCI6MjA2MjE5NTQxNH0.vaknwfVwoUrDU2RqmGCq1J2eGU0gFCPB-fkSnrjACFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);